name: publish package

on:
  workflow_call:
    inputs:
      projname:
        description: 'The name for octo'
        default: 'MISSING PROJECT NAME'
        required: true
        type: string
      projfile:
        description: 'The project file to be built'
        default: 'MISSING PROJECT FILE'
        required: true
        type: string
      projpath:
        description: 'The project path'
        default: 'MISSING PROJECT PATH'
        required: true
        type: string
      solutionfile:
        description: 'The solution file'
        default: ''
        required: false
        type: string        
      majorversion:
        description: 'The first number in the nuget version'
        default: 3
        required: false
        type: number

    secrets:
      OCTOPUS_KEY: 
        required: true
      OCTOPUS_SERVER:
        required: true
      NUGET_RESOURCE_SOURCES:
        required: true

jobs:       
  pack-and-push:
    runs-on: [self-hosted, windows]
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
        
    - name: Restore NuGet Packages
      run: dotnet restore ${{inputs.projpath}}\${{inputs.projfile}} --source "${{secrets.NUGET_RESOURCE_SOURCES}}"
    
    - name: Build and Publish App 
      run: |
           $branch="${{github.ref}}".Split("/")[2]
           $pubFolder="${{ env.GITHUB_WORKSPACE }}/published/${{inputs.projname}}.${{ inputs.majorversion }}.${{ github.run_number }}-$branch/"
           dotnet publish ${{inputs.projpath}}\${{inputs.projfile}} -c Release -o $branch/$pubFolder
      
    - name: 🐙 Octopus
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.6
      with:
          version: latest
    - name: 🐙 Package
      run: |
           $branch="${{github.ref}}".Split("/")[2]
           $pubFolder="${{ env.GITHUB_WORKSPACE }}/published/${{inputs.projname}}.${{ inputs.majorversion }}.${{ github.run_number }}-$branch/"
           octo pack --id="${{inputs.projname}}" --format="zip" --version="${{ inputs.majorversion }}.${{ github.run_number }}-$branch" --basePath="$pubFolder" --outFolder="$GITHUB_WORKSPACE/distoctopus"
    - name: 🐙  Push
      run: |
           $branch="${{github.ref}}".Split("/")[2]
           octo push --package="$GITHUB_WORKSPACE/distoctopus/${{inputs.projname}}.${{ inputs.majorversion }}.${{ github.run_number }}-$branch.zip" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_KEY }}"
