name: publish frmamework nuget

on:
  workflow_call:
    inputs:
      projfile:
        description: 'The path to the project file to be built'
        default: 'MISSING PROJECT FILE'
        required: true
        type: string
    secrets:
      NUGET_SOURCE_MYGET: 
        required: true
      NUGET_RESOURCE_SOURCE: 
        required: true
      MYGET_FEED_SERVER:
        required: true
      MYGET_API_KEY:
        required: true
      MYGET_SYMBOLS_FEED_SERVER:
        required: true
      MYGET_SYMBOLS_API_KEY:
        required: true



jobs:
  pack-and-push:
    runs-on: [self-hosted, windows]

    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1
     
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      
    - name: Build 
      run: msbuild ${{inputs.projfile}} /p:Configuration=Release /t:Rebuild /p:RestoreSources=${{secrets.NUGET_RESOURCE_SOURCE}} 

    - name: pack project 
      run: >
        nuget pack ${{inputs.projfile}} 
        -Prop Configuration=Release 
        -PackagesDirectory packages 
        -version 1.0.${{ github.run_number }}
        -OutputDirectory pub
      
    - name: Publish the package to proget
      run: >
        dotnet nuget push pub/*.nupkg 
        --source ${{secrets.MYGET_FEED_SERVER}} 
        --api-key ${{secrets.MYGET_API_KEY}} 
        --symbol-source ${{secrets.MYGET_SYMBOLS_FEED_SERVER}} 
        -sk ${{secrets.MYGET_SYMBOLS_API_KEY}} 
        --skip-duplicate
